// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5pHIuEjdSXMKvK6UvOWfCtVK7_cIJgtk',
    appId: '1:271493416793:web:5a1b635c42f30a6feb6e48',
    messagingSenderId: '271493416793',
    projectId: 'flash-chat-kurs12',
    authDomain: 'flash-chat-kurs12.firebaseapp.com',
    storageBucket: 'flash-chat-kurs12.appspot.com',
    measurementId: 'G-YXQ6HKRR5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfFwUJgU1mSmrxHy4x7I8fZgPUSOYE5XE',
    appId: '1:271493416793:android:564b46ddc5fbc829eb6e48',
    messagingSenderId: '271493416793',
    projectId: 'flash-chat-kurs12',
    storageBucket: 'flash-chat-kurs12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCwgCtofYrGX6s0fU09iSpe0PyEd27XYE',
    appId: '1:271493416793:ios:0e8936ffa2509e4ceb6e48',
    messagingSenderId: '271493416793',
    projectId: 'flash-chat-kurs12',
    storageBucket: 'flash-chat-kurs12.appspot.com',
    iosClientId:
        '271493416793-dcu7lnjmeo1unqknnqrlnd0grdsgdp4n.apps.googleusercontent.com',
    iosBundleId: 'com.flashchatkurs12.flashChatKurs12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCwgCtofYrGX6s0fU09iSpe0PyEd27XYE',
    appId: '1:271493416793:ios:0e8936ffa2509e4ceb6e48',
    messagingSenderId: '271493416793',
    projectId: 'flash-chat-kurs12',
    storageBucket: 'flash-chat-kurs12.appspot.com',
    iosClientId:
        '271493416793-dcu7lnjmeo1unqknnqrlnd0grdsgdp4n.apps.googleusercontent.com',
    iosBundleId: 'com.flashchatkurs12.flashChatKurs12',
  );
}
